.PHONY: build
build:
	export GO111MODULE=on
	env GOOS=linux go build -ldflags="-s -w" -o bin/v1 v1/*.go

.PHONY: deploy
deploy: build
	sls deploy --verbose

.PHONY: remove
remove:
	sls remove --verbose




